# Generated by Django 5.2.1 on 2025-06-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("ON-HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                    ("IN-PROGRESS", "In Progress"),
                ],
                default="IN-PROGRESS",
                max_length=100,
            ),
        ),
    ]
