# Generated by Django 5.2.2 on 2025-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_assigned_developer_alter_project_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="errors",
            field=models.TextField(
                blank=True,
                help_text="Any errors, blockers, or issues encountered.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="progress_updates",
            field=models.TextField(
                blank=True, help_text="Latest updates on project progress.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("ON-HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                    ("IN-PROGRESS", "In Progress"),
                    ("delayed", "Delayed"),
                ],
                default="IN-PROGRESS",
                max_length=100,
            ),
        ),
    ]
