# Generated by Django 5.2.2 on 2025-06-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0006_alter_project_errors_alter_project_progress_updates_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="progress_updates",
        ),
    ]
