# Generated by Django 5.2.2 on 2025-06-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_remove_task_progress_updates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="assigned_developer",
        ),
    ]
