# Generated by Django 5.2.2 on 2025-06-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_remove_project_assigned_developer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="errors",
        ),
        migrations.RemoveField(
            model_name="project",
            name="progress_updates",
        ),
    ]
